/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f6f3f2",
        "on-tertiary-fixed": "#181c1c",
        "surface-variant": "#e5e2e1",
        "primary-container": "#1a4333",
        "tertiary-container": "#393d3c",
        "on-secondary-fixed-variant": "#005228",
        "secondary": "#006d37",
        "on-background": "#1c1b1b",
        "tertiary-fixed-dim": "#c4c7c6",
        "outline-variant": "#c1c8c2",
        "on-secondary-fixed": "#00210c",
        "primary-fixed": "#c0ecd6",
        "surface-container-highest": "#e5e2e1",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#002115",
        "on-error-container": "#93000a",
        "background": "#fcf9f8",
        "tertiary-fixed": "#e0e3e2",
        "inverse-on-surface": "#f3f0ef",
        "secondary-container": "#6bfe9c",
        "secondary-fixed": "#6bfe9c",
        "surface-bright": "#fcf9f8",
        "on-tertiary-container": "#a4a7a6",
        "surface-container-lowest": "#ffffff",
        "outline": "#717974",
        "inverse-surface": "#313030",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#434847",
        "tertiary": "#232727",
        "on-primary-container": "#85af9b",
        "on-surface": "#1c1b1b",
        "secondary-fixed-dim": "#4ae183",
        "on-surface-variant": "#414844",
        "on-primary-fixed-variant": "#264e3e",
        "inverse-primary": "#a4d0ba",
        "primary-fixed-dim": "#a4d0ba",
        "on-secondary-container": "#00743a",
        "primary": "#002d1e",
        "surface-container-high": "#ebe7e7",
        "surface-dim": "#dcd9d9",
        "surface-container": "#f0edec",
        "surface": "#fcf9f8",
        "surface-tint": "#3e6655"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "sm": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "stack-sm": "12px",
        "gutter": "24px",
        "glass-padding": "24px",
        "stack-md": "24px",
        "container-padding": "32px",
        "base": "8px",
        "md": "16px",
        "xs": "4px",
        "sm": "12px",
        "lg": "24px",
        "xl": "32px",
        "margin-desktop": "40px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        sans: ["Poppins", "Hanken Grotesk", "sans-serif"],
        headline: ["Poppins", "Hanken Grotesk", "sans-serif"],
        body: ["Poppins", "Hanken Grotesk", "sans-serif"],
        label: ["Poppins", "Hanken Grotesk", "sans-serif"],
        title: ["Poppins", "Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Poppins", "sans-serif"],
        "display-lg": ["Poppins", "sans-serif"],
        "body-lg": ["Poppins", "sans-serif"],
        "body-md": ["Poppins", "sans-serif"],
        "label-sm": ["Poppins", "sans-serif"],
        "title-md": ["Poppins", "sans-serif"]
      }
    },
  },
  plugins: [],
}
